import {sqliteTable,text,integer,index,uniqueIndex,primaryKey} from 'drizzle-orm/sqlite-core';
export const settings=sqliteTable('wiki_settings',{id:integer('id').primaryKey(),ownerId:text('owner_id').notNull(),seeded:integer('seeded').notNull().default(0)});
export const members=sqliteTable('members',{id:text('id').primaryKey(),name:text('name').notNull(),email:text('email').notNull(),role:text('role').notNull(),active:integer('active').notNull().default(1),createdAt:integer('created_at').notNull(),invitationId:text('invitation_id')});
export const sections=sqliteTable('sections',{id:text('id').primaryKey(),name:text('name').notNull(),description:text('description').notNull().default(''),color:text('color').notNull().default('purple'),icon:text('icon').notNull().default('code'),position:integer('position').notNull().default(0)});
export const articles=sqliteTable('articles',{id:text('id').primaryKey(),title:text('title').notNull(),sectionId:text('section_id').notNull().references(()=>sections.id),content:text('content').notNull(),format:text('format').notNull().default('markdown'),excerpt:text('excerpt').notNull(),tags:text('tags').notNull().default('[]'),status:text('status').notNull().default('published'),pinned:integer('pinned').notNull().default(0),authorId:text('author_id').notNull(),authorName:text('author_name').notNull(),updatedBy:text('updated_by').notNull(),updatedName:text('updated_name').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),version:integer('version').notNull().default(1),isExample:integer('is_example').notNull().default(0)},t=>[index('idx_articles_section_status').on(t.sectionId,t.status),index('idx_articles_updated').on(t.updatedAt)]);
export const invitations=sqliteTable('invitations',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull(),label:text('label').notNull(),role:text('role').notNull(),maxUses:integer('max_uses').notNull(),uses:integer('uses').notNull().default(0),expiresAt:integer('expires_at').notNull(),createdAt:integer('created_at').notNull(),createdBy:text('created_by').notNull(),revoked:integer('revoked').notNull().default(0)},t=>[uniqueIndex('idx_invitations_token_hash').on(t.tokenHash)]);
export const bookmarks=sqliteTable('bookmarks',{memberId:text('member_id').notNull(),articleId:text('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.memberId,t.articleId]})]);
export const uploads=sqliteTable('uploads',{id:text('id').primaryKey(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),memberId:text('member_id').notNull(),articleId:text('article_id').references(()=>articles.id,{onDelete:'set null'}),createdAt:integer('created_at').notNull()},t=>[index('idx_uploads_article').on(t.articleId)]);
export const revisions=sqliteTable('revisions',{id:text('id').primaryKey(),articleId:text('article_id').notNull().references(()=>articles.id,{onDelete:'cascade'}),title:text('title').notNull(),content:text('content').notNull(),format:text('format').notNull(),version:integer('version').notNull(),authorName:text('author_name').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_revisions_article').on(t.articleId)]);
